version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8888:80"  # HostPort:ContainerPort
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password_here
    volumes:
      - nextcloud:/var/www/html
    networks:
      - nextcloud_network
    #privileged: true

  mysql:
    image: mysql
    container_name: nextcloud_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password_here
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password_here
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - nextcloud_network
    #privileged: true

networks:
  nextcloud_network:

volumes:
  nextcloud:
  mysql:
