version: '3.7'

services:
  webserver1:
    image: httpd:alpine
    container_name: webserver1
    restart: always
    ports:
      - "8081:80"
    volumes:
      - "./website1:/var/www/html/"

  webserver2:
    image: httpd:alpine
    container_name: webserver2
    restart: always
    ports:
      - "8082:80"
    volumes:
      - "./website2:/var/www/html/"